[build]
  # Build command (no cd needed since base is already frontend)
  command = "npm run build"
  
  # Output directory (Next.js static export outputs to 'out' directory)
  publish = "out"
  
  # Base directory
  base = "frontend"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Production environment
  NODE_ENV = "production"

# Next.js specific configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will be set in Netlify dashboard)
[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://your-app.netlify.app"
  NEXT_PUBLIC_API_URL = "https://your-backend-api.com/api/v1"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-$REVIEW_ID--your-app.netlify.app"
  NEXT_PUBLIC_API_URL = "https://your-backend-api.com/api/v1"
